apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../apps/nginx-helm/flux-kustomization.yaml
- alb-controller.yaml
- nginx-ingress-controller.yaml
- shared-alb.yaml
