apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 5m

  chartRef:
    kind: OCIRepository
    name: bitnami-nginx
    namespace: flux-system

  values:
    replicaCount: 1
    service:
      type: ClusterIP
